/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Thu Nov 17 2016 16:05:28 GMT-0700 (Mountain Standard Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
exports.ENV = {};
