/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Wed Nov 02 2016 20:54:22 GMT-0600 (Mountain Daylight Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
exports.ENV = {};
